### PR TITLE
fix usage of @ptrCast, should be @intToPtr

### PR DESCRIPTION
**Pull request by binarycraft007**
Fix as described by commit  message

### CODE REVIEW

**Comment by freiguy1** [comment]
@mattnite I just ran into this problem when starting up a new project. Could this change get reviewed & merged?
```
deps/stmicro-stm32/src/chips/STM32F103.zig:115:30: error: expected 1 argument, found 2
            pub const TIM2 = @ptrCast(*volatile types.TIM2, 0x40000000);
```

**Comment by mattnite** [comment]
@binarycraft007 can you please update the PR by running the 0.11.0 zig fmt on this file? @freiguy1 theres still the inferences typing that was added to builtins.

**Comment by freiguy1** [comment]
Sorry for the ignorance, but I'm not sure what you meant by the part of your comment addressed to me. I did a little digging and found this issue: https://github.com/ziglang/zig/issues/5909 with a couple PRs attached to it. Maybe you were just providing context about _why_ this happened. I'd probably be fine on an older version of zig.

**Comment by binarycraft007** [comment]
> @binarycraft007 can you please update the PR by running the 0.11.0 zig fmt on this file? @freiguy1 theres still the inferences typing that was added to builtins.

just rerun zig fmt on it

**Comment by mattnite** [comment]
@binarycraft007 Thanks! @freiguy1 sorry I was just quickly explaining why I couldn't merge yet. I'm away on a trip but the plan is to stabilize on 0.11.0 for microzig. There was a big change to builtins where they infer their return type instead of having them specified in an argument.

**Pull request merged**
